name: Run Vps Workflow

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/5 * * * *'

jobs:
  run_Vps_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: binary by @0611
        run: chmod +x 0611
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install required packages
        run: |
          pip install telebot pymongo aiohttp

      - name: Run m.py
        run: python3 m.py
        
